FROM mcr.microsoft.com/dotnet/sdk:8.0
WORKDIR /app
COPY BlazorWasmDigitalOcean.csproj BlazorWasmDigitalOcean.csproj
RUN dotnet restore PathfinderCharGen.Web.csproj
COPY . .
RUN dotnet publish -c Release -o /output --no-restore --nologo