// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using PathfinderIM.DataAccess;
using PathfinderIM.Entities.Models;
using System;

namespace PathfinderIM.DataAccess.Migrations
{
    [DbContext(typeof(PathfinderItemContext))]
    [Migration("20200321025828_initialize")]
    partial class initialize
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026");

            modelBuilder.Entity("PathfinderIM.Entities.Models.SourceBook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BookName");

                    b.Property<string>("License");

                    b.Property<int>("PageNumber");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.ToTable("SourceBooks");
                });

            modelBuilder.Entity("PathfinderIM.Entities.Models.WondrousItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<decimal>("GoldPrice");

                    b.Property<string>("Name");

                    b.Property<int>("Slot");

                    b.Property<int?>("SourceId");

                    b.Property<decimal>("Weight");

                    b.HasKey("Id");

                    b.HasIndex("SourceId");

                    b.ToTable("WondrousItems");
                });

            modelBuilder.Entity("PathfinderIM.Entities.Models.WondrousItem", b =>
                {
                    b.HasOne("PathfinderIM.Entities.Models.SourceBook", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId");
                });
#pragma warning restore 612, 618
        }
    }
}
