name: .NET Core

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Release and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal
      - name: Publish
        run: |
          dotnet publish --configuration Release -o pathfinder-manager
      - name: Push code to Digital Ocean
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.REMOTE_HOST }}
          PORT: ${{ secrets.REMOTE_PORT }}
          USERNAME: ${{ secrets.REMOTE_USER }}
          KEY: ${{ secrets.SSHKEY }}
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
        with:
          source: pathfinder-manager
          target: "/var/www/"
