name: .NET Core Deploy

on:
  push:
    branches: [master]
  
  pull_request:
    branches: [master]

  workflow_dispatch:

env:
  REMOTE_APP_FOLDER: "/var/www/"
  APP_USER: www-data

jobs:
  build:
    name: Release and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      # - name: Install dependencies
      #   run: dotnet restore

      # - name: Build
      #   run: |
      #     cd PathfinderCharGen.Web
      #     dotnet build --configuration Release --no-restore

      # - name: Test
      #   run: |
      #     dotnet test --no-restore --verbosity normal

      - name: Publish
        run: |
          dotnet publish --configuration Release -o pathfinder-gen

      - name: Push code to Digital Ocean
        uses: appleboy/scp-action@master
        env:
          USER: ${{ env.APP_USER }}
          REMOTE: ${{ env.REMOTE_APP_FOLDER }}
        with:
          host: ${{ secrets.REMOTE_HOST }}
          port: ${{ secrets.REMOTE_PORT }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSHKEY }}
          source: pathfinder-gen
          target: ${{ env.REMOTE_APP_FOLDER }}
          script: |
            sudo chown -R $USER:$USER $REMOTE
            sudo chmod 755 -R $REMOTE/pathfinder-gen
            sudo chmod g+s -R $REMOTE/pathfinder-gen
          
