name: .NET Core Deploy

on:
  push:
    branches: [master]
  
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    name: Release and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: |
          cd PathfinderCharGen.Web
          dotnet build --configuration Release --no-restore

      - name: Test
        run: |
          dotnet test --no-restore --verbosity normal

      - name: Publish
        run: |
          dotnet publish --configuration Release -o pathfinder-gen

      - name: Push code to Digital Ocean
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          port: ${{ secrets.REMOTE_PORT }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSHKEY }}
          #PASSPHRASE: ${{ secrets.PASSPHRASE }}
          source: pathfinder-gen
          target: "/var/www/"
